name: Daily Python Scraper
on:
  schedule:
    - cron: "0 3 * * *" # 3 AM UTC daily
  workflow_dispatch:
  push:
    branches:
      - main # or 'master' or your active branch

jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps

      - name: Run pipeline
        env:
          DB_HOST: ${{ secrets.CPANEL_DB_HOST }}
          DB_PORT: ${{ secrets.CPANEL_DB_PORT }}
          DB_NAME: ${{ secrets.CPANEL_DB_NAME }}
          DB_USER: ${{ secrets.CPANEL_DB_USER }}
          DB_PASSWORD: ${{ secrets.CPANEL_DB_PASSWORD }}
          GENAI_API_KEY: ${{ secrets.GENAI_API_KEY }}
        run: python main.py
